CREATE TABLE PROVEEDOR (
IDPROVEEDOR INT PRIMARY KEY,
NOMBRE VARCHAR(100),
CONTACTO VARCHAR(50)
)

CREATE TABLE PRODUCTO (
IDPRODUCTO INT PRIMARY KEY,
NOMBRE VARCHAR(100)
)

CREATE TABLE ACTIVIDADES (
IDACTIVIDAD INT PRIMARY KEY,
DESCRIPCION VARCHAR(200),
NUMERODEVISITA INT
)

CREATE TABLE FINCA (
IDFINCA INT PRIMARY KEY,
NOMBRE VARCHAR(100),
DIRECCION VARCHAR(500),
DUENO VARCHAR(100),
CONTACTO VARCHAR(50),
IDPRODUCTO INT
)

ALTER TABLE FINCA 
   ADD CONSTRAINT FK_IDPRODUCTO
   FOREIGN KEY (IDPRODUCTO) 
   REFERENCES PRODUCTO(IDPRODUCTO);
   
CREATE TABLE VISITA (
IDVISITA INT PRIMARY KEY,
NUMERO INT,
DESCRIPCION VARCHAR(500),
FECHA DATE,
IDACTIVIDAD INT,
IDPROVEEDOR INT,
IDFINCA INT
)

ALTER TABLE VISITA 
   ADD CONSTRAINT FK_ACTIVIDAD
   FOREIGN KEY (IDACTIVIDAD) 
   REFERENCES ACTIVIDADES(IDACTIVIDAD);
   
ALTER TABLE VISITA 
   ADD CONSTRAINT FK_PROVEEDOR
   FOREIGN KEY (IDPROVEEDOR) 
   REFERENCES PROVEEDOR(IDPROVEEDOR);
   
ALTER TABLE VISITA 
   ADD CONSTRAINT FK_FINCA
   FOREIGN KEY (IDFINCA) 
   REFERENCES FINCA(IDFINCA);

CREATE TABLE MATERIAPRIMA (
IDMATERIAPRIMA INT PRIMARY KEY,
NOMBRE VARCHAR(100),
DESCRIPCION VARCHAR(1000)
)

CREATE TABLE EMPLEADO (
IDEMPLEADO INT PRIMARY KEY,
NOMBRE VARCHAR(100),
APELLIDO VARCHAR(100),
EDAD INT,
FECHANACIMIENTO DATE,
CARGO VARCHAR(100)
)

CREATE TABLE ORDENDEPRODUCCIONHDR (
IDORDEN INT PRIMARY KEY,
DESCRIPCION VARCHAR(1000),
FECHA DATE
)

CREATE TABLE RECETAHDR(
IDRECETA INT PRIMARY KEY,
DURACION INT,
IDPRODUCTO INT
)

ALTER TABLE RECETAHDR 
   ADD CONSTRAINT FK_RECETAHDR
   FOREIGN KEY (IDPRODUCTO) 
   REFERENCES PRODUCTO(IDPRODUCTO);
   

CREATE TABLE RECETADTL(
IDRECETADETALLE INT PRIMARY KEY,
PERIODICIDAD INT,
IDMATERIAPRIMA INT,
IDRECETA INT
)

ALTER TABLE RECETADTL 
   ADD CONSTRAINT FK_IDRECETA
   FOREIGN KEY (IDRECETA) 
   REFERENCES RECETAHDR(IDRECETA);
   
ALTER TABLE RECETADTL 
   ADD CONSTRAINT FK_MATERIAPRIMA
   FOREIGN KEY (IDMATERIAPRIMA) 
   REFERENCES MATERIAPRIMA(IDMATERIAPRIMA);
   
CREATE TABLE PERSONALORDEN (
IDPERSONAL INT PRIMARY KEY,
IDEMPLEADO INT
)

ALTER TABLE PERSONALORDEN 
   ADD CONSTRAINT FK_PRODUCT
   FOREIGN KEY (IDEMPLEADO) 
   REFERENCES EMPLEADO(IDEMPLEADO);
   
CREATE TABLE ORDENDEPRODUCCIONDTL (
IDORDENDETALLE INT PRIMARY KEY,
IDORDEN INT ,
IDRECETA INT,
IDPERSONAL INT
)

ALTER TABLE ORDENDEPRODUCCIONDTL 
   ADD CONSTRAINT FK_ORDENDEPRODUCCIONDTL
   FOREIGN KEY (IDORDEN) 
   REFERENCES ORDENDEPRODUCCIONHDR(IDORDEN);
   
ALTER TABLE ORDENDEPRODUCCIONDTL 
   ADD CONSTRAINT FK_RECETADTL
   FOREIGN KEY (IDRECETA) 
   REFERENCES RECETAHDR(IDRECETA);

ALTER TABLE ORDENDEPRODUCCIONDTL 
   ADD CONSTRAINT FK_PERSONAL
   FOREIGN KEY (IDPERSONAL) 
   REFERENCES PERSONALORDEN(IDPERSONAL);
   
 CREATE TABLE INVENTARIOHDR(
IDINVENTARIO INT PRIMARY KEY,
TIPO INT,
FECHA DATE
)
   
   
CREATE TABLE INVENTARIODTL(
IDINVENTARIODETALLE INT PRIMARY KEY,
ITEM VARCHAR(100),
EXISTENCIA INT,
IDINVENTARIO INT
)

ALTER TABLE INVENTARIODTL 
   ADD CONSTRAINT FK_INVENTARIO
   FOREIGN KEY (IDINVENTARIO) 
   REFERENCES INVENTARIOHDR(IDINVENTARIO);


CREATE TABLE PLANACTIVIDADES(
IDPLANACTIVIDADES INT PRIMARY KEY,
IDACTIVIDAD INT	
)

ALTER TABLE PLANACTIVIDADES 
   ADD CONSTRAINT FK_ACTIVIDAD
   FOREIGN KEY (IDACTIVIDAD) 
   REFERENCES ACTIVIDADES(IDACTIVIDAD);
   

CREATE TABLE PERSONALVISITA(
IDPERSONALVISITA INT PRIMARY KEY,
IDEMPLEADO INT	
)

ALTER TABLE PERSONALVISITA 
   ADD CONSTRAINT FK_PERSONAL
   FOREIGN KEY (IDEMPLEADO) 
   REFERENCES EMPLEADO(IDEMPLEADO);
   
   
CREATE TABLE PROVEEDORVISITA(
IDPROVEEDORVISITA INT PRIMARY KEY,
IDPROVEEDOR INT	
)

ALTER TABLE PROVEEDORVISITA 
   ADD CONSTRAINT FK_PROVEEDOR
   FOREIGN KEY (IDPROVEEDOR) 
   REFERENCES PROVEEDOR(IDPROVEEDOR);

INSERT INTO VISITA VALUES (3030, 1, 'Vista preliminar', '2019-07-07', 2020, 111, 666)
INSERT INTO VISITA VALUES (3031, 2, 'Vista productiva', '2019-07-07', 2020, 333, 555)
INSERT INTO VISITA VALUES (3032, 3, 'Vista final', '2019-07-07', 2020, 111, 666)

INSERT INTO PROVEEDOR VALUES (111, 'Jose Salinas', '99441928')
INSERT INTO PROVEEDOR VALUES (222, 'Viviana Rosales', '98191928')
INSERT INTO PROVEEDOR VALUES (333, 'Lisian Salinas', '97898728')
SELECT * FROM PROVEEDOR

INSERT INTO PRODUCTO VALUES (1010, 'Uva')
INSERT INTO PRODUCTO VALUES (1011, 'Papa')
INSERT INTO PRODUCTO VALUES (1012, 'Pina')

INSERT INTO FINCA VALUES(555,'Mendez', 'Aldea El Batey', 'Oscar Mendez', '98242198', 1010)
INSERT INTO FINCA VALUES(666,'Lopez', 'Aldea El Llano', 'Emilia Clack', '98242198', 1011)
INSERT INTO FINCA VALUES(777,'Winterfel', 'Aldea El Zacatales', 'Jon Snow', '98242198', 1012)

INSERT INTO ACTIVIDADES VALUES (2020, 'Verificar fertilidad', 1)
INSERT INTO ACTIVIDADES VALUES (2021, 'Verificar humedad', 1)
INSERT INTO ACTIVIDADES VALUES (2022, 'Verificar clima predominante', 1)




