CREATE TABLE PROVEEDOR (
IDPROVEEDOR INT PRIMARY KEY,
NOMBRE VARCHAR(100),
CONTACTO VARCHAR(50)
)

CREATE TABLE PRODUCTO (
IDPRODUCTO INT PRIMARY KEY,
NOMBRE VARCHAR(100)
)

CREATE TABLE ACTIVIDADES (
IDACTIVIDAD INT PRIMARY KEY,
DESCRIPCION VARCHAR(200),
NUMERODEVISITA INT
)

CREATE TABLE FINCA (
IDFINCA INT PRIMARY KEY,
NOMBRE VARCHAR(100),
DIRECCION VARCHAR(500),
DUENO VARCHAR(100),
CONTACTO VARCHAR(50),
IDPRODUCTO INT
)

ALTER TABLE FINCA 
   ADD CONSTRAINT FK_IDPRODUCTO
   FOREIGN KEY (IDPRODUCTO) 
   REFERENCES PRODUCTO(IDPRODUCTO);
   
CREATE TABLE VISITA (
IDVISITA INT PRIMARY KEY,
NUMERO INT,
DESCRIPCION VARCHAR(500),
FECHA DATE,
IDACTIVIDAD INT,
IDPROVEEDOR INT,
IDFINCA INT
)

ALTER TABLE VISITA 
   ADD CONSTRAINT FK_ACTIVIDAD
   FOREIGN KEY (IDACTIVIDAD) 
   REFERENCES ACTIVIDADES(IDACTIVIDAD);
   
ALTER TABLE VISITA 
   ADD CONSTRAINT FK_PROVEEDOR
   FOREIGN KEY (IDPROVEEDOR) 
   REFERENCES PROVEEDOR(IDPROVEEDOR);
   
ALTER TABLE VISITA 
   ADD CONSTRAINT FK_FINCA
   FOREIGN KEY (IDFINCA) 
   REFERENCES FINCA(IDFINCA);

CREATE TABLE MATERIAPRIMA (
IDMATERIAPRIMA INT PRIMARY KEY,
NOMBRE VARCHAR(100),
DESCRIPCION VARCHAR(1000)
)

CREATE TABLE EMPLEADO (
IDEMPLEADO INT PRIMARY KEY,
NOMBRE VARCHAR(100),
APELLIDO VARCHAR(100),
EDAD INT,
FECHANACIMIENTO DATE,
CARGO VARCHAR(100)
)

CREATE TABLE ORDENDEPRODUCCIONHDR (
IDORDEN INT PRIMARY KEY,
DESCRIPCION VARCHAR(1000),
FECHA DATE
)

CREATE TABLE RECETAHDR(
IDRECETA INT PRIMARY KEY,
DURACION INT,
IDPRODUCTO INT
)

ALTER TABLE RECETAHDR 
   ADD CONSTRAINT FK_RECETAHDR
   FOREIGN KEY (IDPRODUCTO) 
   REFERENCES PRODUCTO(IDPRODUCTO);
   

CREATE TABLE RECETADTL(
IDRECETADETALLE INT PRIMARY KEY,
PERIODICIDAD INT,
IDMATERIAPRIMA INT,
IDRECETA INT
)

ALTER TABLE RECETADTL 
   ADD CONSTRAINT FK_IDRECETA
   FOREIGN KEY (IDRECETA) 
   REFERENCES RECETAHDR(IDRECETA);
   
ALTER TABLE RECETADTL 
   ADD CONSTRAINT FK_MATERIAPRIMA
   FOREIGN KEY (IDMATERIAPRIMA) 
   REFERENCES MATERIAPRIMA(IDMATERIAPRIMA);
   
CREATE TABLE PERSONALORDEN (
IDPERSONAL INT PRIMARY KEY,
IDEMPLEADO INT
)

ALTER TABLE PERSONALORDEN 
   ADD CONSTRAINT FK_PRODUCT
   FOREIGN KEY (IDEMPLEADO) 
   REFERENCES EMPLEADO(IDEMPLEADO);
   
CREATE TABLE ORDENDEPRODUCCIONDTL (
IDORDENDETALLE INT PRIMARY KEY,
IDORDEN INT ,
IDRECETA INT,
IDPERSONAL INT
)

ALTER TABLE ORDENDEPRODUCCIONDTL 
   ADD CONSTRAINT FK_ORDENDEPRODUCCIONDTL
   FOREIGN KEY (IDORDEN) 
   REFERENCES ORDENDEPRODUCCIONHDR(IDORDEN);
   
ALTER TABLE ORDENDEPRODUCCIONDTL 
   ADD CONSTRAINT FK_RECETADTL
   FOREIGN KEY (IDRECETA) 
   REFERENCES RECETAHDR(IDRECETA);

ALTER TABLE ORDENDEPRODUCCIONDTL 
   ADD CONSTRAINT FK_PERSONAL
   FOREIGN KEY (IDPERSONAL) 
   REFERENCES PERSONALORDEN(IDPERSONAL);
   
 CREATE TABLE INVENTARIOHDR(
IDINVENTARIO INT PRIMARY KEY,
TIPO INT,
FECHA DATE
)
   
   
CREATE TABLE INVENTARIODTL(
IDINVENTARIODETALLE INT PRIMARY KEY,
ITEM VARCHAR(100),
EXISTENCIA INT,
IDINVENTARIO INT
)

ALTER TABLE INVENTARIODTL 
   ADD CONSTRAINT FK_INVENTARIO
   FOREIGN KEY (IDINVENTARIO) 
   REFERENCES INVENTARIOHDR(IDINVENTARIO);




